- name: common configuration to all node
  hosts: ec2
  user: ec2-user

  roles:
    - common

- name: webserver configuration to Role web
  hosts: tag_Role_web
  user: ec2-user

  roles:
    - webservers
