- name: ensure apache is installed
  yum: pkg=httpd,httpd-devel state=installed

- name: httpd service status
  service: name=httpd state=started enabled=yes

- name: update vhosts config
  tepmlate: src=vhosts.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf
  notify: restart httpd
